---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-node-deployment
  namespace: grocery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-node-deployment
  template:
    metadata:
      labels:
        app: shopping-node-deployment
    spec:
      containers:
        - name: shopping
          image: xdev78/shopping-node:v1
          ports:
            - containerPort: 3502
          env:
            - name: MONGODB_URI
              value: mongodb://mongo:27017/Grocery
---
apiVersion: v1
kind: Service
metadata:
  name: shopping-service
  namespace: grocery
spec:
  type: NodePort
  selector:
    app: shopping-node-deployment
  ports:
    - port: 3502
      targetPort: 3502
      protocol: TCP
      nodePort: 31281
