apiVersion: apps/v1
kind: Deployment
metadata:
  name: grocery-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grocery-frontend
  template:
    metadata:
      labels:
        app: grocery-frontend
    spec:
      containers:
        - name: grocery
          image: xdev78/groceryfrontend:v1
          ports:
            - containerPort: 3000
          env:
            - name: BACKEND_URL
              value: http://gateway-service:8000

---
apiVersion: v1
kind: Service
metadata:
  name: grocery-frontend-service
spec:
  type: NodePort
  selector:
    app: grocery-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000