apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-node-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shopping-node-deployment
  template:
    metadata:
      labels:
        app: shopping-node-deployment
    spec:
      containers:
        - name: shopping-node-image
          image: xdev78/shopping-node:v1
          ports:
            - containerPort: 3502
