---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-node-deployment
  namespace: grocery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-node-deployment
  template:
    metadata:
      labels:
        app: customer-node-deployment
    spec:
      containers:
        - name: customer
          image: xdev78/customer-node:v1
          ports:
            - containerPort: 3501
          env:
            - name: MONGODB_URI
              value: mongodb://mongo:27017/Grocery

---
apiVersion: v1
kind: Service
metadata:
  name: customer-node-service
  namespace: grocery
spec:
  type: NodePort
  selector:
    app: customer-node-deployment
  ports:
    - port: 3501
      targetPort: 3501
      nodePort: 31280
      protocol: TCP

...
