---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-node
  namespace: grocery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-node
  template:
    metadata:
      labels:
        app: gateway-node
    spec:
      containers:
        - name: gateway
          image: xdev78/gateway:v1
          ports:
            - containerPort: 8000
          env:
            - name: CUSTOMER_SERVICE_URL
              value: "http://customer-node-service:3501"
            - name: PRODUCT_SERVICE_URL
              value: "http://product-node-service:3500"
            - name: SHOPPING_SERVICE_URL
              value: "http://shopping-service:3502"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: grocery
spec:
  type: NodePort
  selector:
    app: gateway-node
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 31283
      protocol: TCP
